name: _
publish_to: none
environment:
  sdk: ^3.13.0
workspace:
  - apps/wisp_app
  - apps/wisp_installer
  - packages/wisp_shared
  - packages/wisp_assets
  - packages/wisp_newpipe_manager
  - packages/wisp_ytdlp_manager
  - packages/wisp_playback_engine
  - packages/wisp_audio_output_info

dev_dependencies:
  cider: ^0.2.10