name: wisp_installer
description: "A simple installer."
publish_to: 'none'
version: 26.9.1+13

resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.5.2
  logger: ^2.7.0
  http: ^1.6.0
  archive: ^4.0.9
  path: ^1.9.1
  path_provider: ^2.1.5
  wisp_assets: any
  wisp_newpipe_manager: any
  wisp_ytdlp_manager: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
